---

git_repo: https://github.com/janjic/scania-django.git

project_name: scania_django
application_name: scania_django

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: yes
virtualenv_python_version: python3.6
