# Generated by Django 2.0.2 on 2018-02-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180206_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['nav_cust_name'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mds_customer_id',
            new_name='mds_cust_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nav_cust_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='search_name',
            new_name='nav_cust_search_name',
        ),
    ]
