# Generated by Django 2.0.2 on 2018-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180206_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nav_cust_name',
            field=models.CharField(max_length=250, verbose_name='nav_cust_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nav_cust_search_name',
            field=models.CharField(max_length=250, verbose_name='nav_cust_name'),
        ),
    ]
