# Generated by Django 2.0.2 on 2018-02-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nav_cust_search_name',
            field=models.CharField(max_length=250, verbose_name='nav_cust_search_name'),
        ),
    ]
