# Generated by Django 2.0.2 on 2018-02-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180206_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mds_cust_id',
            field=models.CharField(max_length=250, verbose_name='mds_cust_id'),
        ),
    ]
