# Generated by Django 2.0.2 on 2018-02-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180206_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nav_vat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nav_vat'),
        ),
    ]
